### ISSUE TITLE
@Injectable()

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/ngxs#1]
Figure out how to get rid of having to do @Injectable() along w/ the @Store decorator.

**Comment by deebloo** [comment]
I wonder how @Component() manages it

**Comment by kylecordes** [comment]
The thing that is happening behind the scenes with Angular and Injectable is pretty surprising: basically nothing. The Typescript compiler only preserves constructor type metadata if there is a decorator (any decorator) on the class. By convention, it is recommended to use Injectable as that decorator so it's obvious to the reader why it was done; but **any** decorator works.

Furthermore, the word Injectable isn't quite right. The reason you need to have this metadata preserved so that you can use injection **within** a class. You don't need any decorator at all to make it possible to take a class, provide it for DIA and then inject it to a component.

What happens if you just omit Injectable, on a class where you are already doing some other decorator like Store? You might find it already works.

**Comment by amcdnl** [comment]
Oh interesting! I knew it worked in JIT, but i figured it broke down in AoT.
