### ISSUE TITLE
Can you make examples of the stackblitz?

### ISSUE THREAD

**Issue by splincode** [amcdnl/ngxs#37]

**Comment by amcdnl** [comment]
There is one and a demo app. Will be adding more.

**Comment by slillo** [comment]
I'd like to see an example on stackblitz with actions (not only mutations) as simple as possible.

**Comment by slillo** [comment]
Here is a pretty [simple example](https://stackblitz.com/edit/ngxs-example-basic).

In console.log the state is updated correctly. Also the template is updated correctly.

In redux dev tools the state is updated with a delay of a dispatch. I've the same problem In component, If I set changeDetection to onPush. 

It's like Mutations directly change the state instead of working on a shallow clone of the state. The same happens  returning a new state using:

    return {...state, ...{data: payload}}

**Comment by amcdnl** [comment]
This is kinda an ongoing thing that we will always need. No reason to really track it.
